--- 
:web_client_host: http://70.39.164.61
:openstack_options: 
  :openstack_auth_url: http://70.39.164.61:35357/v2.0/tokens
  :openstack_username: admin
  :openstack_api_key: klnm12
  :openstack_tenant: admin
