---
TTY:
  username: root
  password: password

'CentOS':
  username: root
  password: s3l3ct10n

'Ubuntu':
  username: ubuntu
  password: s3l3ct10n

'Windows':
  username: Administrator
  password: s3l3ct10n
  
'RAW Image Test':
  username: root
  password: s3l3ct10n  
