---
TTY:
  username: root
  password: password

'CentOS':
  username: root
  password: s3l3ct10n

'Ubuntu':
  username: root
  password: s3l3ct10n

'Windows':
  username: Administrator
  password: s3l3ct10n