#!/usr/bin/env bash
# Use this when you are editing features and step definitions
echo "Press Ctrl-C anytime to stop running the tests."
echo "Press Enter to re-run all tests."
rm -rf output/*
bundle exec guard