#!/usr/bin/env bash
description="Automatically runs Bob everytime you change a file"

if [ $# -eq 2 ] && [ $1 == 'describe' ]; then
  printf "  %-0$2s - $description\n" `basename $0`
  exit 0
elif [ $# -eq 1 ] && [ $1 == '--help' ]; then
  printf "Just execute \`run/`basename $0`\` without arguments\n"
  exit 0
fi

echo "Press Ctrl-C anytime to stop autoexecuting Bob"
echo "Press Enter anytime to execute Bob"
rm -rf output/*
bundle exec guard