#!/usr/bin/env ruby
description="Clear all projects and users"

if ARGV.first == "describe" then
  printf "  %-12s - #{description}\n",__FILE__.gsub(/\w+\//,"")
  exit 0
end

with_users  = ARGV.include?('--with_users')
with_images = ARGV.include?('--with_images')
failed      = ARGV.include?('--failed')

# ===========================
#  Warning and Confirmation
# ===========================

print "\033[31mThis will remove all test projects "
print 'and users ' if with_users
print "including those that are possibly in use.\n"
print "Are you sure you want to continue cleaning (Yes)?\033[0m "

exit 0 if STDIN.gets.chomp != 'Yes'


# =============================================
#  Setup required gems, classes, and variable
# =============================================

require 'bundler/setup'
require 'fog'
require 'uri'
require 'net/ssh/gateway'

['environment_cleaner',
 'cloud_configuration',
 'fog_monkey_patch',
 'cloud_services/compute_service',
 'cloud_services/identity_service',
 'cloud_services/image_service',
 'cloud_services/volume_service',
 'tunnel_patch'
].each do |file|
  require_relative "./../features/support/#{ file }"
end

include CloudConfiguration

host = URI.parse(ConfigFile.web_client_url).host
username = ConfigFile.server_username || `whoami`.chomp
tunnel = create_tunnel(host, username) if ConfigFile.tunnel

identity_service = IdentityService.session

# ==============================
#  Register resources to delete
# ==============================

exempted_projects = ConfigFile.cleanup_exemptions[:projects]
exempted_users    = ConfigFile.cleanup_exemptions[:users]
exempted_images   = ConfigFile.cleanup_exemptions[:images]

puts 'Projects to delete:'
puts 'Only removing projects that failed to delete...' if failed

tenants = identity_service.tenants
tenants.delete_if { |tenant| !tenant.name.start_with?('failed') } if failed
tenants.each do |project|
  unless exempted_projects.include? project.name
    puts "  #{project.name}"
    EnvironmentCleaner.register(:project, project.id)
  end
end

if with_users
  puts 'Users to delete:'
  identity_service.users.each do |user|
    unless exempted_users.include? user.name
      puts "  #{user.name}"
      EnvironmentCleaner.register(:user, user.id)
    end
  end
end

if with_images
  puts 'Images to delete:'
  image_service.images.each do |image|
    unless exempted_images.include? image.name
      puts "  #{ image.name }"
      EnvironmentCleaner.register(:image, image.id)
    end
  end
end

# ==============================
#  Delete registered resources
# ==============================
EnvironmentCleaner.delete_test_objects


# ==============================
#  Delete orphaned resources
# ==============================
EnvironmentCleaner.delete_orphans

destroy_tunnel(tunnel) if ConfigFile.tunnel
