#!/usr/bin/env ruby
description = "Configure this copy of mcloud_features"

if ARGV.length == 2 and ARGV[0] == 'describe'
  basename = File.basename(__FILE__).to_s.ljust(ARGV[1].to_i)
  print "  #{basename} - #{description}"
  exit 0
elsif ARGV.length == 1 and ARGV[0] == '--help'
  print "Just execute \`run/#{File.basename(__FILE__)}\` without arguments\n"
  exit 0
end

require 'rubygems'
require 'yaml'
require 'fileutils'

config_path = File.expand_path('../../config.yml', __FILE__)

if File.exists?(config_path) && !ARGV.include?('--force')
  puts "config.yml already exists"
  config_file = File.open(config_path, 'r+')
  config = YAML.load_file(config_file)
  config = {} unless config
else
  puts "\033[0;31m#{config_path} not found. Creating a new config file...\033[0;m"
  config = {}
end

FileUtils.rm_rf(config_path)
config_file = File.open(config_path, File::WRONLY|File::CREAT|File::EXCL)

key = 'host'
if config[key].nil? || config[key].empty?
  print "Which mCloud environment would you like to verify? A blank answer means you will be asked this question everytime the verifier runs: "
  host = STDIN.gets.chomp
  config[key] = host
  unless host.empty?
    config[key] = "http://#{config[key]}" if config[key].match(/^http/).nil?
    config[key] = config[key].gsub(/\/?$/, '')
  end
end

config.delete('cloud_admin_username')

key = 'cloud_admin_email'
if config[key].nil? || config[key].empty?
  print "Cloud Admin email for #{config['host']}: "
  host = STDIN.gets.chomp
  config[key] = host
end

key = 'cloud_admin_password'
if config[key].nil? || config[key].empty?
  print "Password for #{config['cloud_admin_email']}: "
  host = STDIN.gets.chomp
  config[key] = host
end

puts "Writing #{config_path}"
YAML.dump(config, config_file)