#!/usr/bin/env bash
description="Validates a specific feature instead of all features"

if [ $# -eq 2 ] && [ $1 == 'describe' ]; then
  printf "  %-0$2s - $description\n" `basename $0`
  exit 0
elif [ $# -eq 1 ] && [ $1 == '--help' ]; then
  printf "run/`basename $0` <path_to_feature_file>\n"
  printf "Examples:\n"
  printf "  run/`basename $0` features/categories/authentication/logging_in.feature\n"
  printf "  run/`basename $0` features/categories/users/create_a_user.feature\n"
  exit 0
fi

bundle exec cucumber $1 --profile single_feature