#!/usr/bin/env bash
description="Generates a permissions matrix"

if [ $# -eq 2 ] && [ $1 == 'describe' ]; then
  printf "  %-0$2s - $description\n" `basename $0`
  exit 0
elif [ $# -eq 1 ] && [ $1 == '--help' ]; then
  printf "run/`basename $0` [path_to_output_dir]\n\n"
  printf "Examples:\n"
  printf "  run/`basename $0`\n"
  printf "  run/`basename $0` ~/Dropbox/permissions\n\n"
  exit 0
fi

if [ $# -eq 1 ]; then
  OUTDIR=$1
else
  OUTDIR=output/permissions
fi

bundle exec cucumber --tags @permissions --no-profile --require features --dry-run --format Cucumber::Formatter::Relaxdiego::PermissionsMatrix --out $OUTDIR --require features