#!/usr/bin/env bash
description="Setup dependencies and configure mcloud_features"

if [ $# -eq 2 ] && [ $1 == 'describe' ]; then
  printf "  %-0$2s - $description\n" `basename $0`
  exit 0
elif [ $# -eq 1 ] && [ $1 == '--help' ]; then
  printf "Just execute \`run/`basename $0`\` without arguments\n"
  exit 0
fi

ruby_string="ruby 1.9"

if ruby --version | grep -q "${ruby_string}" ; then
  echo "${ruby_string} found!"
else
  echo "${ruby_string} or higher must be installed."
  echo "Please install it before proceeding"
  exit 1
fi


if bundle --version | grep "Bundler version"; then
  echo "Bundler gem found!"
else
  echo "Installing Bundler gem..."
  gem install bundler
fi
bundle update
run/configurator
echo "Setup is complete. Now type 'run/verifier' or 'run/autoverifier' (without the quotes)"