#!/usr/bin/env ruby
description = 'Validates features that have a given tag'

basename = File.basename(__FILE__).to_s
if ARGV[0] == 'describe'
  puts "  #{basename.ljust(ARGV[1].to_i)} - #{description}"
  exit 0
elsif ARGV.length == 1 && ARGV[1] == '--help'
  puts <<HELP
Usage: run/#{basename} tag1[,tag2,tag3] [options]
Separate tags by a ',' (no spaces) to run more than one tag.
HELP
  exit 0
end

require 'rubygems'
require 'bundler/setup'
require 'fog'
require 'yaml'
require 'fileutils'
require 'uri'
['cloud_configuration',
 'fog_monkey_patch',
 'tunnel_patch'
].each do |file|
  require_relative File.expand_path("../../features/support/#{ file }", __FILE__)
end

include CloudConfiguration

require_relative File.expand_path('../../features/support/sauce', __FILE__) if ConfigFile.capybara_driver == 'sauce'
host = URI.parse(ConfigFile.web_client_url).host
username = ConfigFile.server_username || `whoami`.chomp
tunnel = create_tunnel(host, username) if ConfigFile.tunnel

puts "Verifying requirements tagged with #{ARGV[0]}"
puts "Start at #{Time.now}"
system "bundle exec cucumber --no-profile --tags #{ARGV[0]} --require features --format Cucumber::Formatter::Bob::Html --out output --format rerun --out rerun.txt --format 'Slowhandcuke::Formatter'"
destroy_tunnel(tunnel) if ConfigFile.tunnel
puts "Finished at #{Time.now}"
