#!/usr/bin/env bash
description="Pull latest changes from a remote repo and call run/setup"

if [ $# -eq 2 ] && [ $1 == 'describe' ]; then
  printf "  %-0$2s - $description\n" `basename $0`
  exit 0
elif [ $# -eq 1 ] && [ $1 == '--help' ]; then
  printf "run/`basename $0` [remote] [branch]\n\n"
  printf "Examples:\n"
  printf "  run/`basename $0`\n"
  printf "  run/`basename $0` wdamarillo master\n\n"
  printf "IMPORTANT: 'remote' and 'branch' must already be configured in .git/config\n"
  printf "\nIf 'remote' and 'branch' are not specified, they default to 'origin' and 'master' respectively\n"
  exit 0
fi


if [ $# -ne 2 ]; then
  REMOTE='origin'
  BRANCH='master'
else
  REMOTE=$1
  BRANCH=$2
fi
echo -e "Pulling latest changes from $REMOTE/$BRANCH..."
git pull $1 $2
echo -e "Running run/setup..."
run/setup
echo "Your local repo has been updated. Have a nice day!"