#!/usr/bin/env bash
description="Verifies all features"

if [ $# -eq 2 ] && [ $1 == 'describe' ]; then
  printf "  %-0$2s - $description\n" `basename $0`
  exit 0
elif [ $# -eq 1 ] && [ $1 == '--help' ]; then
  printf "run/`basename $0` <profile>\n"
  printf "\nExamples:\n"
  printf "  run/`basename $0`\n"
  printf "  run/`basename $0` ci\n"
  printf "  run/`basename $0` wip\n"
  printf "\nSee cucumber.yml for available profiles\n"
  exit 0
fi

rm -rf output/*
if [ $# -eq 1 ]; then
  bundle exec cucumber --profile $1 --t ~@future --t ~@pending
elif [ $# -eq 2 ]; then
  bundle exec cucumber --profile $1 --t ~@future --t ~@pending --t $2
else
  bundle exec cucumber --profile default --t ~@future --t ~@pending
fi
